# coding: utf-8

"""
    Virtual Infrastructure JSON API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 8.0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class CannotUseNetworkReasonEnum(str, Enum):
    """
    Possible values: - `NetworkReservationNotSupported`: Network does not support reservation - `MismatchedNetworkPolicies`: Source and destination networks do not have same security policies - `MismatchedDvsVersionOrVendor`: Source and destination DVS do not have same version or vendor - `VMotionToUnsupportedNetworkType`: VMotion to unsupported destination network type - `NetworkUnderMaintenance`: The network is under maintenance      ***Since:*** vSphere API 7.0 - `MismatchedEnsMode`: Source and destination networks do not have same ENS(Enhanced Network Stack) mode      ***Since:*** vSphere API 7.0  ***Since:*** vSphere API 5.5 
    """

    """
    allowed enum values
    """
    NETWORKRESERVATIONNOTSUPPORTED = 'NetworkReservationNotSupported'
    MISMATCHEDNETWORKPOLICIES = 'MismatchedNetworkPolicies'
    MISMATCHEDDVSVERSIONORVENDOR = 'MismatchedDvsVersionOrVendor'
    VMOTIONTOUNSUPPORTEDNETWORKTYPE = 'VMotionToUnsupportedNetworkType'
    NETWORKUNDERMAINTENANCE = 'NetworkUnderMaintenance'
    MISMATCHEDENSMODE = 'MismatchedEnsMode'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of CannotUseNetworkReasonEnum from a JSON string"""
        return cls(json.loads(json_str))


