# coding: utf-8

"""
    Virtual Infrastructure JSON API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 8.0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class HostLowLevelProvisioningManagerFileTypeEnum(str, Enum):
    """
    This enum defines the possible types of file types that can be reserved or deleted  Possible values: - `File` - `VirtualDisk` - `Directory`  ***Since:*** vSphere API 6.0 
    """

    """
    allowed enum values
    """
    FILE = 'File'
    VIRTUALDISK = 'VirtualDisk'
    DIRECTORY = 'Directory'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of HostLowLevelProvisioningManagerFileTypeEnum from a JSON string"""
        return cls(json.loads(json_str))


