# coding: utf-8

"""
    Virtual Infrastructure JSON API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 8.0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class HostSgxInfoSgxStatesEnum(str, Enum):
    """
    Host SGX states.  Possible values: - `notPresent`: SGX is not present in the CPU. - `disabledBIOS`: SGX is disabled in the BIOS. - `disabledCFW101`: SGX is disabled because CPU erratum CFW101 is present. - `disabledCPUMismatch`: SGX is disabled due to a mismatch in the SGX capabilities   exposed by different CPUs. - `disabledNoFLC`: SGX is disabled because the CPU does not support FLC. - `disabledNUMAUnsup`: SGX is disabled because the host uses NUMA, which is not   supported with SGX. - `disabledMaxEPCRegs`: SGX is disabled because the host exceeds the maximum supported   number of EPC regions. - `enabled`: SGX is enabled.    ***Since:*** vSphere API 7.0 
    """

    """
    allowed enum values
    """
    NOTPRESENT = 'notPresent'
    DISABLEDBIOS = 'disabledBIOS'
    DISABLEDCFW101 = 'disabledCFW101'
    DISABLEDCPUMISMATCH = 'disabledCPUMismatch'
    DISABLEDNOFLC = 'disabledNoFLC'
    DISABLEDNUMAUNSUP = 'disabledNUMAUnsup'
    DISABLEDMAXEPCREGS = 'disabledMaxEPCRegs'
    ENABLED = 'enabled'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of HostSgxInfoSgxStatesEnum from a JSON string"""
        return cls(json.loads(json_str))


