# coding: utf-8

"""
    Virtual Infrastructure JSON API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 8.0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class HostProfileManagerAnswerFileStatusEnum(str, Enum):
    """
    The *HostProfileManagerAnswerFileStatus_enum* enum defines possible values for answer file status.  Possible values: - `valid`: Answer file is valid. - `invalid`: Answer file is not valid.      The file is either missing or incomplete.   - To produce an answer file, pass host-specific data (user input) to the     *HostProfileManager*.*HostProfileManager.ApplyHostConfig_Task*     method.   - To produce a complete answer file, call the     *HostProfile*.*HostProfile.ExecuteHostProfile*     method and fill in any missing parameters in the returned     *ProfileExecuteResult*.*ProfileExecuteResult.requireInput*     list. After you execute the profile successfully, you can pass the complete required     input list to the apply method. - `unknown`: Answer file status is not known.    ***Since:*** vSphere API 5.0 
    """

    """
    allowed enum values
    """
    VALID = 'valid'
    INVALID = 'invalid'
    UNKNOWN = 'unknown'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of HostProfileManagerAnswerFileStatusEnum from a JSON string"""
        return cls(json.loads(json_str))


