# coding: utf-8

"""
    Virtual Infrastructure JSON API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 8.0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class HostNvmeTransportTypeEnum(str, Enum):
    """
    The set of NVM Express over Fabrics transport types.  For details, see: - \"NVM Express over Fabrics 1.0\", Section 1.5.1,   \"Fabrics and Transports\".    Possible values: - `pcie`: PCI Express transport type - `fibreChannel`: Fibre Channel transport type - `rdma`: Remote Direct Memory Access transport type - `tcp`: Transmission Control Protocol transport type      ***Since:*** vSphere API 7.0.3.0 - `loopback`: Intra-host transport. - `unsupported`: The transport type is not among the currently supported ones.    ***Since:*** vSphere API 7.0 
    """

    """
    allowed enum values
    """
    PCIE = 'pcie'
    FIBRECHANNEL = 'fibreChannel'
    RDMA = 'rdma'
    TCP = 'tcp'
    LOOPBACK = 'loopback'
    UNSUPPORTED = 'unsupported'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of HostNvmeTransportTypeEnum from a JSON string"""
        return cls(json.loads(json_str))


