# coding: utf-8

"""
    Virtual Infrastructure JSON API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 8.0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class NvdimmNamespaceTypeEnum(str, Enum):
    """
    Type of namespace.  Possible values: - `blockNamespace`: Block mode namespace - `persistentNamespace`: Persistent mode namespace    ***Since:*** vSphere API 6.7 
    """

    """
    allowed enum values
    """
    BLOCKNAMESPACE = 'blockNamespace'
    PERSISTENTNAMESPACE = 'persistentNamespace'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NvdimmNamespaceTypeEnum from a JSON string"""
        return cls(json.loads(json_str))


