# coding: utf-8

"""
    Virtual Infrastructure JSON API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 8.0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class PhysicalNicResourcePoolSchedulerDisallowedReasonEnum(str, Enum):
    """
    Possible values: - `userOptOut`: Indicates that the user has opted out the Physical NIC from resource pool   based scheduling. - `hardwareUnsupported`: Indicates that the NIC device does is not capable of resource pool   based scheduling.    ***Since:*** vSphere API 4.1 
    """

    """
    allowed enum values
    """
    USEROPTOUT = 'userOptOut'
    HARDWAREUNSUPPORTED = 'hardwareUnsupported'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PhysicalNicResourcePoolSchedulerDisallowedReasonEnum from a JSON string"""
        return cls(json.loads(json_str))


