# coding: utf-8

"""
    Virtual Infrastructure JSON API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 8.0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class ScheduledHardwareUpgradeInfoHardwareUpgradePolicyEnum(str, Enum):
    """
    The policy setting used to determine when to perform scheduled upgrades for a virtual machine.  Possible values: - `never`: No scheduled upgrades. - `onSoftPowerOff`: Run scheduled upgrades only on normal guest OS shutdown. - `always`: Always run scheduled upgrades.    ***Since:*** vSphere API 5.1 
    """

    """
    allowed enum values
    """
    NEVER = 'never'
    ONSOFTPOWEROFF = 'onSoftPowerOff'
    ALWAYS = 'always'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ScheduledHardwareUpgradeInfoHardwareUpgradePolicyEnum from a JSON string"""
        return cls(json.loads(json_str))


