# coding: utf-8

"""
    Virtual Infrastructure JSON API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 8.0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class UpgradePolicyEnum(str, Enum):
    """
    The policy setting used to determine when tools are auto-upgraded for a virtual machine  Possible values: - `manual`: No auto-upgrades for tools will be performed for this   virtual machine.      Users must manually invoke the UpgradeTools   operation to update the tools. - `upgradeAtPowerCycle`: When the virtual machine is power-cycled, the system checks   for a newer version of tools when the VM comes back up.      If it   is available, a tools upgrade is automatically performed on the   virtual machine and it is rebooted if necessary.  ***Since:*** VI API 2.5 
    """

    """
    allowed enum values
    """
    MANUAL = 'manual'
    UPGRADEATPOWERCYCLE = 'upgradeAtPowerCycle'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UpgradePolicyEnum from a JSON string"""
        return cls(json.loads(json_str))


