# coding: utf-8

"""
    Virtual Infrastructure JSON API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 8.0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class VirtualDiskRuleSpecRuleTypeEnum(str, Enum):
    """
    Rule type determines how the virtual disks in a vm can be grouped together.  Possible values: - `affinity`: Virtual disks in the list are grouped together and placed on   the same data store. - `antiAffinity`: Virtual disks in the list are placed on different data stores. - `disabled`: SDRS will be disabled for the disks in the list.    ***Since:*** vSphere API 6.7 
    """

    """
    allowed enum values
    """
    AFFINITY = 'affinity'
    ANTIAFFINITY = 'antiAffinity'
    DISABLED = 'disabled'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of VirtualDiskRuleSpecRuleTypeEnum from a JSON string"""
        return cls(json.loads(json_str))


