# coding: utf-8

"""
    Virtual Infrastructure JSON API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 8.0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
import re  # noqa: F401
from enum import Enum



try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class VirtualDeviceURIBackingOptionDirectionEnum(str, Enum):
    """
    The <code>VirtualDeviceURIBackingOptionDirection</code> enum type provides values for the direction of a network connection.  Possible values: - `server`: Indicates that the virtual machine can listen for a connection   on the specified *VirtualDeviceURIBackingInfo.serviceURI*. - `client`: Indicates that the virtual machine can initiate a connection   with a system on the network using the specified   *VirtualDeviceURIBackingInfo.serviceURI*.    ***Since:*** vSphere API 4.1 
    """

    """
    allowed enum values
    """
    SERVER = 'server'
    CLIENT = 'client'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of VirtualDeviceURIBackingOptionDirectionEnum from a JSON string"""
        return cls(json.loads(json_str))


